package com.dorama.avatar

import ai.onnxruntime.*
import android.content.ContentValues
import android.graphics.*
import android.media.*
import android.net.Uri
import android.os.Bundle
import android.provider.MediaStore
import android.provider.OpenableColumns
import android.widget.*
import androidx.activity.result.contract.ActivityResultContracts
import androidx.appcompat.app.AppCompatActivity
import com.google.mlkit.vision.common.InputImage
import com.google.mlkit.vision.face.FaceDetection
import com.google.mlkit.vision.face.FaceDetectorOptions
import java.io.File
import java.net.URL
import java.nio.FloatBuffer
import kotlin.concurrent.thread
import kotlin.math.*

class MainActivity:AppCompatActivity(){
 private var imageUri:Uri?=null;private var audioUri:Uri?=null;private lateinit var status:TextView;private lateinit var preview:ImageView;private lateinit var progress:ProgressBar
 private val imagePicker=registerForActivityResult(ActivityResultContracts.OpenDocument()){u->u?.let{imageUri=it;preview.setImageURI(it);status.text="✓ Картинка: ${name(it)}"}}
 private val audioPicker=registerForActivityResult(ActivityResultContracts.OpenDocument()){u->u?.let{audioUri=it;status.text="✓ WAV: ${name(it)}"}}
 override fun onCreate(b:Bundle?){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.status);preview=findViewById(R.id.preview);progress=findViewById(R.id.progress);findViewById<Button>(R.id.imageButton).setOnClickListener{imagePicker.launch(arrayOf("image/*"))};findViewById<Button>(R.id.audioButton).setOnClickListener{audioPicker.launch(arrayOf("audio/*"))};findViewById<Button>(R.id.modelButton).setOnClickListener{downloadModel()};findViewById<Button>(R.id.generateButton).setOnClickListener{generateMp4()}}
 private fun modelFile()=File(filesDir,"wav2lip.onnx")
 private fun downloadModel(){if(modelFile().exists()&&modelFile().length()>100_000_000){status.text="✓ Модель уже скачана: ${modelFile().length()/1024/1024} МБ";return};thread{try{runOnUiThread{status.text="Скачиваю Wav2Lip ONNX…";progress.progress=0};val con=URL("https://huggingface.co/bluefoxcreation/Wav2lip-Onnx/resolve/main/wav2lip.onnx?download=true").openConnection();val total=con.contentLengthLong;con.getInputStream().use{i->modelFile().outputStream().use{o->val buf=ByteArray(262144);var n:Int;var done=0L;while(i.read(buf).also{n=it}>0){o.write(buf,0,n);done+=n;if(total>0)runOnUiThread{progress.progress=(done*100/total).toInt()}}}};runOnUiThread{status.text="✓ Модель скачана"}}catch(e:Exception){runOnUiThread{status.text="Ошибка загрузки: ${e.message}"}}}}
 private fun generateMp4(){if(imageUri==null||audioUri==null){status.text="Сначала выбери картинку и WAV.";return};if(!modelFile().exists()){status.text="Сначала скачай модель кнопкой 3.";return};thread{try{val started=System.currentTimeMillis();runOnUiThread{status.text="V0.3: готовлю лицо и звук…";progress.progress=1};val original=contentResolver.openInputStream(imageUri!!)!!.use{BitmapFactory.decodeStream(it)};val face=detectFace(original);val wav=contentResolver.openInputStream(audioUri!!)!!.use{WavUtils.readPcm16(it)};val mel=WavUtils.melSpectrogram(wav.samples);val env=OrtEnvironment.getEnvironment();val session=env.createSession(modelFile().absolutePath,OrtSession.SessionOptions());val names=session.inputNames.toList();val melName=names.firstOrNull{it.contains("mel",true)}?:names[0];val imgName=names.firstOrNull{it.contains("video",true)||it.contains("frame",true)||it.contains("img",true)}?:names.last();val cropInfo=cropInfo(original,face);val crop96=Bitmap.createScaledBitmap(Bitmap.createBitmap(original,cropInfo[0],cropInfo[1],cropInfo[2],cropInfo[2]),96,96,true);val imgTensor=makeImageTensor(crop96);val frameCount=min(125,max(1,((wav.samples.size/16000f)*25).toInt()));val frames=ArrayList<Bitmap>(frameCount)
  for(f in 0 until frameCount){val mi=(f*80.0/25.0).toInt().coerceAtMost(max(0,mel[0].size-16));val mf=FloatArray(80*16);for(y in 0 until 80)for(x in 0 until 16)mf[y*16+x]=mel[y][(mi+x).coerceAtMost(mel[y].lastIndex)];val patch=OnnxTensor.createTensor(env,FloatBuffer.wrap(mf),longArrayOf(1,1,80,16)).use{mt->OnnxTensor.createTensor(env,FloatBuffer.wrap(imgTensor),longArrayOf(1,6,96,96)).use{itn->session.run(mapOf(melName to mt,imgName to itn)).use{r->outputBitmap(r[0].value)}}};frames.add(pasteBack(original,patch,cropInfo));if(f%2==0)runOnUiThread{progress.progress=5+(f*65/frameCount);status.text="Генерирую губы: ${f+1}/$frameCount"}}
  session.close();val maxW=720;val scale=min(1f,maxW.toFloat()/original.width);var w=((original.width*scale).toInt()/2)*2;var h=((original.height*scale).toInt()/2)*2;w=max(2,w);h=max(2,h);val video=encodeVideo(frames,w,h);frames.forEach{if(it!==original)it.recycle()};runOnUiThread{progress.progress=78;status.text="Кодирую звук AAC…"};val audio=encodeAudio(wav.samples,16000);runOnUiThread{progress.progress=90;status.text="Собираю MP4…"};val uri=saveMuxed(video,audio);val sec=(System.currentTimeMillis()-started)/1000.0;runOnUiThread{progress.progress=100;status.text="✓ V0.3 ГОТОВА\n✓ ${frameCount} кадров / ${"%.1f".format(frameCount/25.0)} сек\n✓ H.264 + AAC\n✓ MP4 сохранён в Movies/DoramaAvatar\n⏱ ${"%.1f".format(sec)} сек\n\nОткрой видео и пришли, как выглядят губы.";Toast.makeText(this,"MP4 сохранён",Toast.LENGTH_LONG).show()}}
  catch(e:Throwable){runOnUiThread{status.text="Ошибка V0.3: ${e.javaClass.simpleName}: ${e.message}"}}}}
 data class Sample(val data:ByteArray,val info:MediaCodec.BufferInfo)
 data class Encoded(val format:MediaFormat,val samples:List<Sample>)
 private fun encodeVideo(src:List<Bitmap>,w:Int,h:Int):Encoded{val fmt=MediaFormat.createVideoFormat(MediaFormat.MIMETYPE_VIDEO_AVC,w,h);fmt.setInteger(MediaFormat.KEY_COLOR_FORMAT,MediaCodecInfo.CodecCapabilities.COLOR_FormatYUV420SemiPlanar);fmt.setInteger(MediaFormat.KEY_BIT_RATE,2_500_000);fmt.setInteger(MediaFormat.KEY_FRAME_RATE,25);fmt.setInteger(MediaFormat.KEY_I_FRAME_INTERVAL,1);val c=MediaCodec.createEncoderByType(MediaFormat.MIMETYPE_VIDEO_AVC);c.configure(fmt,null,null,MediaCodec.CONFIGURE_FLAG_ENCODE);c.start();val out=ArrayList<Sample>();var of:MediaFormat?=null;val bi=MediaCodec.BufferInfo();for((i,b) in src.withIndex()){val idx=c.dequeueInputBuffer(10000);if(idx>=0){val scaled=if(b.width==w&&b.height==h)b else Bitmap.createScaledBitmap(b,w,h,true);val yuv=toNV12(scaled,w,h);if(scaled!==b)scaled.recycle();c.getInputBuffer(idx)!!.apply{clear();put(yuv)};c.queueInputBuffer(idx,0,yuv.size,i*40000L,if(i==src.lastIndex)MediaCodec.BUFFER_FLAG_END_OF_STREAM else 0)};drain(c,bi,out){of=it}}
  var loops=0;while(loops++<100&&out.none{it.info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM!=0})drain(c,bi,out){of=it};c.stop();c.release();return Encoded(of?:throw RuntimeException("Нет video format"),out)}
 private fun encodeAudio(x:FloatArray,sr:Int):Encoded{val fmt=MediaFormat.createAudioFormat(MediaFormat.MIMETYPE_AUDIO_AAC,sr,1);fmt.setInteger(MediaFormat.KEY_AAC_PROFILE,MediaCodecInfo.CodecProfileLevel.AACObjectLC);fmt.setInteger(MediaFormat.KEY_BIT_RATE,96000);val c=MediaCodec.createEncoderByType(MediaFormat.MIMETYPE_AUDIO_AAC);c.configure(fmt,null,null,MediaCodec.CONFIGURE_FLAG_ENCODE);c.start();val out=ArrayList<Sample>();var of:MediaFormat?=null;val bi=MediaCodec.BufferInfo();var pos=0;while(pos<x.size){val idx=c.dequeueInputBuffer(10000);if(idx>=0){val n=min(1024,x.size-pos);val buf=c.getInputBuffer(idx)!!;buf.clear();for(i in 0 until n){val s=(x[pos+i].coerceIn(-1f,1f)*32767).toInt();buf.put((s and 255).toByte());buf.put((s shr 8).toByte())};c.queueInputBuffer(idx,0,n*2,pos*1_000_000L/sr,0);pos+=n};drain(c,bi,out){of=it}};val idx=c.dequeueInputBuffer(10000);if(idx>=0)c.queueInputBuffer(idx,0,0,pos*1_000_000L/sr,MediaCodec.BUFFER_FLAG_END_OF_STREAM);var loops=0;while(loops++<100&&out.none{it.info.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM!=0})drain(c,bi,out){of=it};c.stop();c.release();return Encoded(of?:throw RuntimeException("Нет audio format"),out)}
 private fun drain(c:MediaCodec,bi:MediaCodec.BufferInfo,out:MutableList<Sample>,format:(MediaFormat)->Unit){while(true){val oi=c.dequeueOutputBuffer(bi,0);if(oi==MediaCodec.INFO_TRY_AGAIN_LATER)return;if(oi==MediaCodec.INFO_OUTPUT_FORMAT_CHANGED){format(c.outputFormat);continue};if(oi>=0){val b=c.getOutputBuffer(oi)!!;if(bi.size>0){b.position(bi.offset);b.limit(bi.offset+bi.size);val d=ByteArray(bi.size);b.get(d);val copy=MediaCodec.BufferInfo();copy.set(0,bi.size,bi.presentationTimeUs,bi.flags);out.add(Sample(d,copy))};c.releaseOutputBuffer(oi,false);if(bi.flags and MediaCodec.BUFFER_FLAG_END_OF_STREAM!=0)return}}}
 private fun saveMuxed(v:Encoded,a:Encoded):Uri{val cv=ContentValues().apply{put(MediaStore.Video.Media.DISPLAY_NAME,"DoramaAvatar_${System.currentTimeMillis()}.mp4");put(MediaStore.Video.Media.MIME_TYPE,"video/mp4");put(MediaStore.Video.Media.RELATIVE_PATH,"Movies/DoramaAvatar");put(MediaStore.Video.Media.IS_PENDING,1)};val uri=contentResolver.insert(MediaStore.Video.Media.EXTERNAL_CONTENT_URI,cv)?:throw RuntimeException("Не удалось создать MP4");contentResolver.openFileDescriptor(uri,"w")!!.use{pfd->val m=MediaMuxer(pfd.fileDescriptor,MediaMuxer.OutputFormat.MUXER_OUTPUT_MPEG_4);val vt=m.addTrack(v.format);val at=m.addTrack(a.format);m.start();v.samples.forEach{if(it.info.size>0)m.writeSampleData(vt,java.nio.ByteBuffer.wrap(it.data),it.info)};a.samples.forEach{if(it.info.size>0)m.writeSampleData(at,java.nio.ByteBuffer.wrap(it.data),it.info)};m.stop();m.release()};cv.clear();cv.put(MediaStore.Video.Media.IS_PENDING,0);contentResolver.update(uri,cv,null,null);return uri}
 private fun outputBitmap(v:Any?):Bitmap{val a=v as Array<*>;val c0=a[0] as Array<*>;val pix=IntArray(96*96);for(y in 0 until 96)for(x in 0 until 96){fun ch(c:Int):Int{val row=(c0[c] as Array<*>)[y] as FloatArray;return (row[x].coerceIn(0f,1f)*255).toInt()};pix[y*96+x]=Color.rgb(ch(0),ch(1),ch(2))};return Bitmap.createBitmap(pix,96,96,Bitmap.Config.ARGB_8888)}
 private fun pasteBack(base:Bitmap,patch:Bitmap,ci:IntArray):Bitmap{val out=base.copy(Bitmap.Config.ARGB_8888,true);val c=Canvas(out);val dst=Rect(ci[0],ci[1],ci[0]+ci[2],ci[1]+ci[2]);val p=Paint(Paint.ANTI_ALIAS_FLAG);c.drawBitmap(patch,null,dst,p);patch.recycle();return out}
 private fun cropInfo(b:Bitmap,r:Rect):IntArray{val cx=(r.left+r.right)/2;val cy=(r.top+r.bottom)/2;val s=(max(r.width(),r.height())*1.5).toInt().coerceAtMost(min(b.width,b.height));val l=(cx-s/2).coerceIn(0,b.width-s);val t=(cy-s/2).coerceIn(0,b.height-s);return intArrayOf(l,t,s)}
 private fun toNV12(b:Bitmap,w:Int,h:Int):ByteArray{val argb=IntArray(w*h);b.getPixels(argb,0,w,0,0,w,h);val yuv=ByteArray(w*h*3/2);var yi=0;var uvi=w*h;for(j in 0 until h)for(i in 0 until w){val p=argb[j*w+i];val r=Color.red(p);val g=Color.green(p);val bl=Color.blue(p);val y=((66*r+129*g+25*bl+128 shr 8)+16).coerceIn(0,255);val u=((-38*r-74*g+112*bl+128 shr 8)+128).coerceIn(0,255);val v=((112*r-94*g-18*bl+128 shr 8)+128).coerceIn(0,255);yuv[yi++]=y.toByte();if(j%2==0&&i%2==0){yuv[uvi++]=u.toByte();yuv[uvi++]=v.toByte()}};return yuv}
 private fun detectFace(b:Bitmap):Rect{val opt=FaceDetectorOptions.Builder().setPerformanceMode(FaceDetectorOptions.PERFORMANCE_MODE_ACCURATE).build();val task=FaceDetection.getClient(opt).process(InputImage.fromBitmap(b,0));while(!task.isComplete)Thread.sleep(20);if(!task.isSuccessful)throw task.exception?:RuntimeException("Face detector");val faces=task.result?:emptyList();if(faces.isEmpty())throw RuntimeException("Лицо не найдено");return faces.maxBy{it.boundingBox.width()*it.boundingBox.height()}.boundingBox}
 private fun makeImageTensor(b:Bitmap):FloatArray{val pix=IntArray(9216);b.getPixels(pix,0,96,0,0,96,96);val out=FloatArray(55296);for(y in 0 until 96)for(x in 0 until 96){val p=pix[y*96+x];val rgb=floatArrayOf(Color.red(p)/255f,Color.green(p)/255f,Color.blue(p)/255f);for(c in 0..2){val z=rgb[c];out[c*9216+y*96+x]=if(y<48)0f else z;out[(c+3)*9216+y*96+x]=z}};return out}
 private fun name(u:Uri):String{contentResolver.query(u,null,null,null,null)?.use{c->val i=c.getColumnIndex(OpenableColumns.DISPLAY_NAME);if(c.moveToFirst()&&i>=0)return c.getString(i)};return u.lastPathSegment?:"file"}
}
